### ISSUE TITLE
Put_Bulk is bailing out  when encounter "No Such File exception"  -- with version v3.2.5-RC1

### ISSUE THREAD

**Issue by omoba123** [SpectraLogic/ds3_java_cli#160]
Hello,

# cat Filelist | ds3_java_cli -c put_bulk -b Test2 -nt 5 --sync --verbose --http

When we run put_bulk of ds3_java_cli with sync option as below on our live production system to backup to our spectralogic T590 tape via Blackpearl Gateway. It is bailing out when encounter the first occurrence of temporary files that existed at one point but has been deleted afterwards by our applications processes. 

We encounter same issues when the java client encounter Unix special files such as pipe,socket or fifo.  Can this issue be handle such that the client will log this issues, then skip such special files or non-existent files but continue with other files/objects o completion. The same way it skips symbolic links  but logs it. 
This bug is serious as once a non-existent files is encounter, it will write the names of all objects from that point onwards but with no checksum and ETAG of "N/A". The issue is made worse as subsequent sync operation will report no need to sync... all files are up to date even though they are fluke files. The only way we have been coping is by having to delete those files (thousands) from the bucket and then re-run the bulk put. Most of the time, we have to iterate multiple times as the non-existent files location is not predictable.

"2017-01-17 16:09:33 +++ Failed to check the status of a file
java.nio.file.NoSuchFileException: .test/home/ds3dir/file_6MB
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:97)
	at java.nio.file.Files.readAttributes(Files.java:1686)
	at java.nio.file.Files.getLastModifiedTime(Files.java:2209)
	at com.spectralogic.ds3cli.util.SyncUtils.isNewFile(SyncUtils.java:53)
	at com.spectralogic.ds3cli.command.PutBulk$SyncFilter.filter(PutBulk.java:255)
	at com.spectralogic.ds3cli.command.PutBulk$SyncFilter.filter(PutBulk.java:227)
	at com.spectralogic.ds3cli.util.FilteringIterable$FilteringIterator.getNext(FilteringIterable.java:68)
	at com.spectralogic.ds3cli.util.FilteringIterable$FilteringIterator.next(FilteringIterable.java:60)
	at com.spectralogic.ds3cli.util.FileUtils.getObjectsToPut(FileUtils.java:68)
	at com.spectralogic.ds3cli.command.PutBulk.call(PutBulk.java:158)
	at com.spectralogic.ds3cli.command.PutBulk.call(PutBulk.java:54)
	at com.spectralogic.ds3cli.command.CliCommand.render(CliCommand.java:177)
	at com.spectralogic.ds3cli.Main.main(Main.java:194)
2017-01-17 16:09:33 +++ No need to sync ttest/home/ds3dir/file_22MB
2017-01-17 16:09:33 +++ No need to sync test/home/ds3dir/file_1MB
2017-01-17 16:09:33 +++ No need to sync test/home/ds3dir/file_21MB
2017-01-17 16:09:33 +++ No need to sync test/home/ds3dir/file_GB
2017-01-17 16:09:33 +++ No need to sync test/home/ds3dir/oyo/dir4/funk2
2017-01-17 16:09:33 +++ No need to sync test/home/ds3dir/oyo/dir4/fu
.
.
Thanks

**Comment by omoba123** [comment]
Addition....
I tried --ignore-errors option but this did not work as it reported that all files are up to date even when those files were fluke --- not the right size and no checksum or ETAG. Also clean up the objects and re-ran with afresh with ---ignore-errors but no effect.

I also tried running put bulk without sync first and then ran the job again with --ignore-naming-conflicts to see if it will work like sync.. that is to ignore the earlier successfully copied files with same size and correct check sum ... to fool it to copy only the files that did not check-sum correctly earlier.

Please any help to point us in the right direction will be appreciated.

**Comment by rpmoore** [comment]
This is an outstanding feature enhancement that we are currently working on.  Expect for there to be an update in a couple weeks that should address your major issues.

**Comment by omoba123** [comment]
Thank you very much Ryan!

Looking forward to this update with great enthusiasm.

Ade

**Comment by rpmoore** [comment]
Just wanted to follow up on this.  The latest pre-release version includes a fix to the issue that you were seeing.  If you'd like, give it a try and let us know if you continue to run into any problems with it.
